spring.application.name=actbrow
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.datasource.url=jdbc:postgresql://localhost:5432/actbrow
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=actbrow
spring.datasource.password=actbrow
spring.h2.console.enabled=false
actbrow.agent.max-steps=6
actbrow.agent.tool-timeout=10s
actbrow.llm.default-provider=sarvam
actbrow.gemini.base-url=https://generativelanguage.googleapis.com/v1beta
actbrow.gemini.default-model=gemini-2.5-flash
actbrow.gemini.request-timeout=20s
actbrow.gemini.api-key=
actbrow.sarvam.base-url=https://api.sarvam.ai/v1
actbrow.sarvam.default-model=sarvam-m
actbrow.sarvam.request-timeout=20s
actbrow.sarvam.api-key=sk_zarprsog_vTwwR7eH0Upxm2WPpTrudifu
actbrow.cors.allowed-origins=http://localhost:3000
